server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/prac_security?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: Hc-5514
    password: 5514
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#spring:
#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:3306/prac_security?serverTimezone=Asia/Seoul
#    username: Hc-5514
#    password: 5514
#
#  jpa:
#    hibernate:
#      ddl-auto: create #create update none
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    show-sql: true
#    database-platform: org.hibernate.dialect.MariaDB103Dialect